from z3 import*
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]==117,buttons[2]+buttons[3]==15,buttons[1]==2,buttons[0]+buttons[1]+buttons[2]+buttons[3]==128)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[5]==12,buttons[2]+buttons[3]+buttons[5]==12,buttons[0]+buttons[3]+buttons[4]==13,buttons[0]+buttons[2]+buttons[4]==13,buttons[2]+buttons[4]==2,buttons[1]+buttons[2]+buttons[4]+buttons[5]==31,buttons[1]+buttons[3]+buttons[4]==19)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[7]+buttons[9]+buttons[10]==51,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]+buttons[9]==33,buttons[1]+buttons[5]+buttons[10]==24,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[6]+buttons[9]==38,buttons[1]+buttons[8]==16,buttons[2]+buttons[6]+buttons[10]==22,buttons[1]+buttons[2]+buttons[4]+buttons[7]+buttons[9]+buttons[10]==58,buttons[0]+buttons[1]+buttons[4]+buttons[9]==25,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[8]+buttons[9]+buttons[10]==54,buttons[1]+buttons[2]+buttons[4]+buttons[7]+buttons[9]==44)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(2) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]==9,buttons[0]==1,buttons[0]+buttons[1]==9,buttons[0]+buttons[1]==9)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[4]==43,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==59,buttons[3]==16,buttons[1]+buttons[3]+buttons[4]+buttons[5]==39,buttons[0]+buttons[2]+buttons[4]==38,buttons[0]+buttons[1]+buttons[4]==25)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[5]==24,buttons[2]+buttons[3]+buttons[5]+buttons[7]==40,buttons[0]+buttons[1]+buttons[3]+buttons[7]==67,buttons[4]+buttons[5]+buttons[6]==26,buttons[4]+buttons[5]+buttons[6]+buttons[7]==42,buttons[1]+buttons[3]+buttons[5]==34,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]==62,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[6]==64,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[6]==81,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[6]==64)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]+buttons[4]+buttons[7]==44,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[7]==44,buttons[1]+buttons[2]+buttons[3]+buttons[7]+buttons[8]==44,buttons[1]+buttons[5]+buttons[6]+buttons[8]==36,buttons[0]+buttons[1]+buttons[2]==12,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[6]==42,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[7]==46,buttons[0]+buttons[2]+buttons[4]+buttons[8]==36,buttons[1]+buttons[2]+buttons[3]==27)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[4]+buttons[5]==32,buttons[1]+buttons[2]+buttons[3]+buttons[4]==32,buttons[0]==0,buttons[0]+buttons[2]+buttons[3]+buttons[5]==21,buttons[1]+buttons[2]+buttons[4]+buttons[5]==27)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==87,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[6]==53,buttons[3]+buttons[5]+buttons[6]+buttons[7]==62,buttons[0]+buttons[3]==21,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[7]==73,buttons[2]+buttons[6]==18,buttons[0]+buttons[1]==25)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[7]+buttons[8]==190,buttons[0]+buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==192,buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[8]==169,buttons[0]+buttons[5]+buttons[6]+buttons[8]==50,buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[8]==50,buttons[0]+buttons[5]+buttons[6]+buttons[7]==45,buttons[0]+buttons[3]==147,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[8]==196,buttons[0]+buttons[2]+buttons[5]+buttons[8]==48,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==203)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(12) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[5]+buttons[8]+buttons[11]==29,buttons[1]+buttons[3]+buttons[5]+buttons[7]+buttons[8]+buttons[9]+buttons[11]==70,buttons[1]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[10]+buttons[11]==55,buttons[1]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[9]==43,buttons[1]+buttons[7]+buttons[9]+buttons[10]==37,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[7]+buttons[10]==57,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[8]+buttons[9]==36,buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[9]==32,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[9]+buttons[11]==57,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[10]==63)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[4]+buttons[5]==161,buttons[1]+buttons[3]==25,buttons[1]+buttons[2]+buttons[4]+buttons[5]==177,buttons[0]+buttons[1]+buttons[2]+buttons[4]==164,buttons[0]+buttons[1]+buttons[2]==148,buttons[0]+buttons[2]+buttons[3]+buttons[4]==157,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==186)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]==15,buttons[0]+buttons[3]+buttons[4]==43,buttons[0]+buttons[1]+buttons[2]==31,buttons[2]+buttons[3]==21,buttons[0]+buttons[3]+buttons[5]==32)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[4]+buttons[5]==35,buttons[0]+buttons[3]+buttons[4]==23,buttons[1]+buttons[2]+buttons[4]==19,buttons[1]+buttons[2]+buttons[5]==31,buttons[2]+buttons[3]+buttons[4]==21,buttons[2]+buttons[3]+buttons[4]==21,buttons[2]+buttons[5]==30,buttons[0]+buttons[2]+buttons[3]==31)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[6]+buttons[7]+buttons[8]==65,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==216,buttons[1]+buttons[4]+buttons[6]+buttons[7]+buttons[8]==59,buttons[0]+buttons[2]+buttons[5]+buttons[7]+buttons[8]==183,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[8]==62,buttons[0]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==184,buttons[1]+buttons[8]==20,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==202)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[6]+buttons[7]+buttons[8]==49,buttons[0]+buttons[3]+buttons[4]+buttons[7]+buttons[8]==63,buttons[0]+buttons[1]+buttons[4]==35,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[8]==69,buttons[0]+buttons[2]+buttons[5]+buttons[7]==44,buttons[0]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==57,buttons[4]+buttons[8]==29,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]+buttons[7]+buttons[8]==84)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[3]==31,buttons[0]+buttons[3]+buttons[4]==138,buttons[0]+buttons[3]+buttons[4]==138,buttons[0]+buttons[1]+buttons[2]==22,buttons[1]==0)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[4]+buttons[6]==40,buttons[3]+buttons[5]==8,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[6]==43,buttons[0]+buttons[1]+buttons[2]+buttons[6]==219,buttons[1]+buttons[4]+buttons[6]==35,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]==237,buttons[0]+buttons[1]+buttons[2]+buttons[3]==221)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[4]+buttons[5]==31,buttons[1]+buttons[3]+buttons[4]+buttons[5]==34,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]==62,buttons[1]+buttons[2]+buttons[3]==33,buttons[0]+buttons[1]+buttons[5]==21)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]==28,buttons[2]+buttons[3]+buttons[7]+buttons[8]==52,buttons[2]+buttons[5]+buttons[9]==36,buttons[0]+buttons[2]+buttons[3]+buttons[6]+buttons[7]+buttons[8]+buttons[9]==101,buttons[0]+buttons[2]+buttons[3]+buttons[6]+buttons[8]==81,buttons[0]+buttons[1]+buttons[6]+buttons[8]+buttons[9]==72,buttons[1]+buttons[2]+buttons[4]+buttons[6]+buttons[7]+buttons[8]+buttons[9]==90,buttons[1]+buttons[5]+buttons[6]+buttons[8]+buttons[9]==60,buttons[2]+buttons[3]+buttons[7]+buttons[8]==52,buttons[4]+buttons[7]+buttons[8]+buttons[9]==45)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[4]+buttons[5]==34,buttons[1]+buttons[4]==21,buttons[1]+buttons[2]+buttons[4]+buttons[5]==23,buttons[3]+buttons[4]+buttons[5]==25,buttons[5]==2,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==41,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]==36)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[7]==45,buttons[1]+buttons[2]+buttons[3]+buttons[7]==23,buttons[2]+buttons[5]+buttons[6]==17,buttons[5]+buttons[7]==19,buttons[0]+buttons[3]+buttons[6]==19,buttons[1]+buttons[4]+buttons[7]==30,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[7]==45,buttons[3]+buttons[5]+buttons[6]+buttons[7]==31,buttons[0]+buttons[2]+buttons[5]+buttons[6]+buttons[7]==34)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]+buttons[6]==45,buttons[2]+buttons[3]==11,buttons[3]+buttons[4]==25,buttons[0]+buttons[2]+buttons[3]+buttons[6]==44,buttons[0]+buttons[1]+buttons[2]+buttons[5]==47,buttons[1]+buttons[2]+buttons[3]==18,buttons[1]+buttons[2]+buttons[4]+buttons[5]==50,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[6]==51)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[4]==18,buttons[1]+buttons[3]+buttons[4]==23,buttons[1]+buttons[2]+buttons[3]==21,buttons[3]+buttons[4]==20,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]==34,buttons[0]+buttons[1]==9)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(2) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]==155,buttons[0]==5,buttons[1]==155,buttons[0]+buttons[1]==160)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(3) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]==144,buttons[0]+buttons[1]==37,buttons[0]==19,buttons[0]+buttons[2]==145)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]+buttons[6]+buttons[9]==60,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[8]+buttons[9]==91,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[7]==78,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[7]+buttons[8]+buttons[9]==95,buttons[5]+buttons[6]+buttons[8]+buttons[9]==42,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[9]==82,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[8]+buttons[9]==88,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==66,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[9]==106,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[7]+buttons[8]+buttons[9]==78)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[5]+buttons[7]+buttons[8]==55,buttons[0]+buttons[3]+buttons[6]+buttons[7]==40,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[7]+buttons[8]==81,buttons[0]+buttons[2]+buttons[5]+buttons[8]==33,buttons[2]+buttons[3]+buttons[7]+buttons[8]==48,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[7]+buttons[8]==54,buttons[1]+buttons[6]==33)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]+buttons[7]==30,buttons[0]+buttons[2]+buttons[4]+buttons[6]+buttons[7]==45,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[7]==48,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==46,buttons[1]+buttons[2]+buttons[4]+buttons[7]==30,buttons[0]+buttons[1]+buttons[4]+buttons[6]==30,buttons[1]+buttons[5]==16,buttons[1]+buttons[2]+buttons[6]+buttons[7]==27)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]==115,buttons[1]==110,buttons[0]+buttons[1]==114,buttons[0]+buttons[2]+buttons[3]==17,buttons[0]+buttons[1]+buttons[2]+buttons[3]==127)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]==13,buttons[0]+buttons[4]==22,buttons[1]==19,buttons[1]+buttons[2]+buttons[3]+buttons[4]==63,buttons[0]+buttons[1]+buttons[4]==41,buttons[0]+buttons[1]+buttons[2]+buttons[3]==53)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[4]==38,buttons[0]+buttons[4]==20,buttons[1]+buttons[2]+buttons[3]==37,buttons[2]+buttons[3]+buttons[4]==37)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]==199,buttons[3]==15,buttons[1]==15,buttons[2]==19)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[4]==7,buttons[1]+buttons[3]+buttons[6]==20,buttons[0]+buttons[1]+buttons[3]+buttons[6]==21,buttons[0]+buttons[1]+buttons[5]+buttons[6]==30,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]==45,buttons[0]+buttons[5]+buttons[6]==17)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]==25,buttons[1]+buttons[3]==23,buttons[0]==16,buttons[1]==6,buttons[0]+buttons[1]+buttons[2]==30)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==51,buttons[0]+buttons[2]+buttons[5]==19,buttons[0]+buttons[1]+buttons[5]==23,buttons[1]+buttons[2]+buttons[4]+buttons[5]==26,buttons[0]+buttons[4]==18,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==51,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==37)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[5]==23,buttons[0]+buttons[1]+buttons[3]==12,buttons[0]+buttons[3]+buttons[5]+buttons[6]==25,buttons[2]+buttons[3]+buttons[4]+buttons[5]==40,buttons[0]+buttons[1]+buttons[3]+buttons[5]==28,buttons[0]+buttons[1]+buttons[4]+buttons[6]==26)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[5]+buttons[7]+buttons[8]==24,buttons[2]+buttons[7]+buttons[8]==18,buttons[0]+buttons[5]+buttons[8]==13,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[7]+buttons[8]==37,buttons[0]+buttons[1]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==59,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==48,buttons[1]+buttons[3]+buttons[6]+buttons[8]==32,buttons[1]+buttons[2]+buttons[5]+buttons[7]==18,buttons[4]+buttons[5]+buttons[7]==31)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]==2,buttons[0]+buttons[3]==11,buttons[3]+buttons[4]==19,buttons[0]+buttons[2]+buttons[3]+buttons[4]==41,buttons[1]==3,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]==44)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[4]==11,buttons[1]+buttons[2]+buttons[4]==21,buttons[1]+buttons[3]==22,buttons[0]+buttons[2]+buttons[5]==30)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[5]==22,buttons[0]+buttons[1]+buttons[2]==40,buttons[2]+buttons[3]+buttons[4]+buttons[5]==54,buttons[1]+buttons[2]+buttons[3]==25,buttons[1]+buttons[2]+buttons[4]+buttons[5]==54)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]==169,buttons[0]+buttons[1]+buttons[2]+buttons[3]==215,buttons[2]+buttons[3]==185,buttons[0]+buttons[1]+buttons[2]==199,buttons[0]+buttons[2]==180,buttons[0]+buttons[1]==30)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[4]+buttons[6]+buttons[9]+buttons[10]==40,buttons[0]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[9]+buttons[10]==73,buttons[4]+buttons[6]+buttons[7]+buttons[8]+buttons[9]==52,buttons[3]+buttons[4]+buttons[9]==7,buttons[1]+buttons[4]+buttons[6]+buttons[7]+buttons[8]+buttons[9]+buttons[10]==76,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[7]+buttons[10]==284,buttons[3]+buttons[4]+buttons[10]==25,buttons[2]+buttons[5]+buttons[7]+buttons[9]==232,buttons[3]+buttons[4]+buttons[7]+buttons[9]==21)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[7]==225,buttons[2]+buttons[4]+buttons[5]+buttons[6]==217,buttons[6]+buttons[7]==19,buttons[2]+buttons[4]+buttons[6]+buttons[7]==215,buttons[0]+buttons[4]+buttons[7]==31,buttons[1]+buttons[4]+buttons[7]==40,buttons[1]+buttons[2]+buttons[5]+buttons[7]==233,buttons[2]+buttons[3]+buttons[4]+buttons[7]==213,buttons[0]+buttons[1]+buttons[4]+buttons[7]==43,buttons[0]+buttons[1]+buttons[2]+buttons[4]==211)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]==46,buttons[0]+buttons[3]+buttons[4]+buttons[7]==50,buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==51,buttons[0]+buttons[1]+buttons[2]+buttons[6]==43,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[7]==60,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[7]==69,buttons[0]+buttons[1]+buttons[2]+buttons[5]==50,buttons[1]+buttons[2]+buttons[3]+buttons[7]==43,buttons[0]+buttons[2]+buttons[6]+buttons[7]==53,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[7]+buttons[8]==85)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[5]==31,buttons[2]+buttons[3]+buttons[4]==36,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==185,buttons[0]+buttons[1]+buttons[2]==154,buttons[0]+buttons[3]+buttons[5]+buttons[6]==63)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[7]==47,buttons[1]+buttons[3]+buttons[4]==28,buttons[3]+buttons[4]==24,buttons[0]+buttons[2]+buttons[3]+buttons[5]==53,buttons[1]+buttons[4]+buttons[7]+buttons[8]==31,buttons[1]+buttons[4]+buttons[5]+buttons[8]==46,buttons[2]+buttons[5]+buttons[6]==48)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]+buttons[7]+buttons[8]==52,buttons[1]+buttons[3]+buttons[5]+buttons[6]+buttons[7]==56,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[7]==51,buttons[0]+buttons[1]+buttons[3]+buttons[6]+buttons[8]==51,buttons[1]+buttons[2]+buttons[6]+buttons[7]+buttons[8]==56,buttons[1]+buttons[4]+buttons[6]+buttons[7]+buttons[8]==56,buttons[1]+buttons[4]+buttons[6]+buttons[7]==52,buttons[3]+buttons[4]+buttons[7]+buttons[8]==46,buttons[1]+buttons[2]+buttons[6]+buttons[7]==52)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[6]==23,buttons[1]+buttons[3]+buttons[4]+buttons[9]==16,buttons[0]+buttons[2]+buttons[4]+buttons[8]+buttons[9]==32,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[8]+buttons[9]==65,buttons[0]+buttons[3]+buttons[4]+buttons[6]+buttons[8]==57,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[7]+buttons[9]==42,buttons[0]+buttons[2]+buttons[5]==30,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[8]+buttons[9]==78,buttons[0]+buttons[2]+buttons[4]+buttons[8]+buttons[9]==32)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]==13,buttons[0]+buttons[4]==20,buttons[0]+buttons[1]+buttons[4]==29,buttons[0]+buttons[2]+buttons[3]==29)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]==10,buttons[0]+buttons[2]==11,buttons[2]==6,buttons[0]+buttons[1]+buttons[3]==180)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]==5,buttons[0]==4,buttons[1]+buttons[2]+buttons[3]==7,buttons[0]+buttons[3]==4)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]==31,buttons[0]+buttons[2]+buttons[3]==42,buttons[2]+buttons[4]==19,buttons[1]+buttons[4]==23)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(12) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[11]==75,buttons[5]+buttons[6]+buttons[7]+buttons[10]==58,buttons[2]+buttons[5]+buttons[6]+buttons[11]==45,buttons[2]+buttons[3]+buttons[5]+buttons[9]+buttons[10]==69,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[9]==72,buttons[5]+buttons[7]+buttons[10]==41,buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[10]==79,buttons[1]+buttons[2]+buttons[5]+buttons[7]+buttons[10]==69,buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[11]==59,buttons[2]+buttons[4]+buttons[7]+buttons[9]==38)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[6]+buttons[7]==49,buttons[0]+buttons[3]+buttons[4]==54,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==68,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[7]==91,buttons[4]+buttons[6]==21,buttons[3]+buttons[4]+buttons[6]==41)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]+buttons[4]+buttons[6]==24,buttons[1]+buttons[2]+buttons[5]+buttons[6]==38,buttons[0]+buttons[2]+buttons[6]==32,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==54,buttons[0]+buttons[2]+buttons[3]==30,buttons[0]+buttons[1]+buttons[5]+buttons[6]==41,buttons[2]+buttons[3]+buttons[6]==23,buttons[2]+buttons[3]+buttons[4]+buttons[6]==30,buttons[0]+buttons[1]==19)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[9]==39,buttons[1]+buttons[4]+buttons[5]+buttons[9]==45,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[8]==96,buttons[0]+buttons[1]+buttons[5]+buttons[7]+buttons[8]+buttons[9]==92,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[7]+buttons[8]==110,buttons[0]+buttons[6]+buttons[7]+buttons[8]+buttons[9]==77,buttons[0]+buttons[1]+buttons[3]+buttons[6]+buttons[9]==79,buttons[1]+buttons[8]==30,buttons[1]+buttons[3]+buttons[5]+buttons[7]+buttons[8]==73,buttons[0]+buttons[2]+buttons[4]+buttons[8]+buttons[9]==77)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(3) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]==21,buttons[0]+buttons[1]+buttons[2]==200,buttons[0]+buttons[1]+buttons[2]==200,buttons[0]==10,buttons[1]+buttons[2]==190)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[6]==30,buttons[1]+buttons[2]+buttons[6]==31,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[6]==39,buttons[2]+buttons[3]+buttons[6]==30,buttons[0]+buttons[1]+buttons[5]+buttons[6]==32,buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==54,buttons[1]+buttons[3]+buttons[5]==19,buttons[6]==13,buttons[1]+buttons[4]==18)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(3) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]==7,buttons[0]+buttons[1]==21,buttons[2]==4,buttons[0]==3,buttons[0]+buttons[1]+buttons[2]==25)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[4]+buttons[5]==22,buttons[3]+buttons[5]+buttons[6]==38,buttons[2]+buttons[3]==18,buttons[2]+buttons[4]+buttons[6]==28,buttons[2]+buttons[4]+buttons[6]==28,buttons[1]+buttons[3]+buttons[4]+buttons[6]==42,buttons[0]+buttons[4]==14,buttons[2]+buttons[5]+buttons[6]==32,buttons[2]+buttons[3]+buttons[4]+buttons[6]==40)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[7]+buttons[8]==23,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]==44,buttons[1]+buttons[2]+buttons[4]+buttons[5]==44,buttons[0]+buttons[5]+buttons[6]==23,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]==41,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==62,buttons[1]+buttons[4]+buttons[5]+buttons[7]==38,buttons[0]+buttons[2]+buttons[3]+buttons[4]==42)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]+buttons[5]==11,buttons[0]+buttons[5]+buttons[6]==11,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[6]==22,buttons[0]+buttons[1]+buttons[3]+buttons[6]==20,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[6]==38,buttons[0]+buttons[1]+buttons[4]==24,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==36,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[6]==22)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[3]+buttons[6]==37,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]==46,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[7]==56,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==62,buttons[4]+buttons[5]+buttons[7]==29,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[7]==56,buttons[1]+buttons[3]+buttons[6]+buttons[7]==30,buttons[1]+buttons[2]+buttons[3]+buttons[6]+buttons[7]==44)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]==19,buttons[0]+buttons[4]==3,buttons[1]+buttons[2]+buttons[3]+buttons[4]==55,buttons[1]+buttons[4]==17)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[5]+buttons[6]+buttons[7]==53,buttons[0]+buttons[3]+buttons[5]==23,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[6]+buttons[7]==69,buttons[4]+buttons[5]+buttons[7]==30,buttons[0]+buttons[2]==2,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]==42)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[4]+buttons[5]==20,buttons[2]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==31,buttons[0]+buttons[2]+buttons[6]+buttons[7]==19,buttons[0]+buttons[1]==10,buttons[2]+buttons[5]+buttons[7]==16,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[8]==44,buttons[2]+buttons[4]+buttons[5]+buttons[9]==34,buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==35)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(13) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[5]+buttons[7]+buttons[9]+buttons[11]==53,buttons[1]+buttons[2]+buttons[3]+buttons[6]+buttons[7]+buttons[9]+buttons[11]==76,buttons[2]+buttons[3]+buttons[4]+buttons[9]+buttons[11]==67,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[11]==83,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[7]+buttons[11]+buttons[12]==58,buttons[1]+buttons[3]+buttons[5]+buttons[8]+buttons[9]==35,buttons[0]+buttons[1]+buttons[5]+buttons[7]+buttons[9]+buttons[11]==58,buttons[0]+buttons[2]+buttons[3]+buttons[7]+buttons[8]+buttons[10]+buttons[12]==45,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[7]+buttons[11]==42,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[10]+buttons[11]+buttons[12]==72)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]+buttons[4]==49,buttons[0]+buttons[1]+buttons[4]==44,buttons[0]+buttons[1]+buttons[2]+buttons[4]==59,buttons[0]+buttons[2]+buttons[4]==41,buttons[0]+buttons[3]+buttons[4]==46,buttons[0]+buttons[3]==35,buttons[1]==18)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[8]+buttons[9]==42,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[8]==95,buttons[3]+buttons[5]+buttons[6]+buttons[8]==32,buttons[1]+buttons[2]+buttons[4]+buttons[7]==54,buttons[0]+buttons[6]+buttons[8]==30,buttons[1]+buttons[3]+buttons[6]+buttons[9]==35,buttons[0]+buttons[3]+buttons[4]+buttons[6]+buttons[8]+buttons[9]==68,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[8]==82)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[5]+buttons[6]==26,buttons[0]+buttons[4]+buttons[5]+buttons[6]+buttons[7]==65,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==45,buttons[5]==12,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[7]==40,buttons[0]+buttons[1]+buttons[2]+buttons[5]==32,buttons[1]+buttons[2]+buttons[4]==23,buttons[1]+buttons[2]+buttons[3]==12,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]==40)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(3) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]==27,buttons[1]==10,buttons[0]+buttons[2]==26,buttons[0]+buttons[2]==26)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[5]==32,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==52,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==49,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]==43,buttons[0]+buttons[2]==24,buttons[0]+buttons[3]+buttons[4]==25,buttons[3]+buttons[5]==17)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[4]+buttons[5]==32,buttons[0]+buttons[1]+buttons[2]+buttons[5]==53,buttons[1]+buttons[3]+buttons[4]+buttons[5]==41,buttons[0]+buttons[4]+buttons[5]==42,buttons[2]+buttons[3]==14,buttons[0]+buttons[1]+buttons[4]==31)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]+buttons[4]==48,buttons[3]+buttons[4]==15,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[7]==51,buttons[2]+buttons[4]+buttons[5]+buttons[6]==48,buttons[0]+buttons[2]+buttons[5]+buttons[7]==58,buttons[0]+buttons[2]+buttons[5]==41,buttons[1]+buttons[4]+buttons[7]==36,buttons[0]+buttons[3]+buttons[5]+buttons[6]+buttons[7]==61)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]==3,buttons[0]+buttons[2]+buttons[5]==28,buttons[0]+buttons[3]+buttons[4]+buttons[5]==39,buttons[1]+buttons[2]==11,buttons[3]+buttons[5]==9,buttons[1]+buttons[3]==12)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]+buttons[5]+buttons[7]==40,buttons[6]==12,buttons[2]==17,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==82,buttons[1]+buttons[4]+buttons[5]+buttons[6]==64,buttons[0]+buttons[2]+buttons[4]+buttons[5]==62)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]==26,buttons[3]+buttons[4]==14,buttons[1]+buttons[2]+buttons[4]==15,buttons[0]+buttons[2]+buttons[3]+buttons[4]==41,buttons[0]+buttons[1]+buttons[2]+buttons[3]==40,buttons[1]+buttons[2]+buttons[3]+buttons[4]==28,buttons[2]+buttons[3]+buttons[4]==28)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[4]+buttons[5]==41,buttons[0]+buttons[3]==154,buttons[1]+buttons[3]+buttons[4]+buttons[5]==46,buttons[1]+buttons[2]+buttons[5]==34)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[6]+buttons[7]==36,buttons[2]+buttons[3]+buttons[4]==29,buttons[3]+buttons[5]+buttons[7]+buttons[8]==20,buttons[3]+buttons[4]+buttons[7]==20,buttons[0]+buttons[2]+buttons[3]+buttons[7]==26,buttons[0]+buttons[3]+buttons[4]==13,buttons[1]+buttons[3]+buttons[4]+buttons[6]+buttons[7]==147,buttons[1]+buttons[2]+buttons[5]==138)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==70,buttons[0]+buttons[3]+buttons[4]+buttons[7]+buttons[8]+buttons[9]==53,buttons[2]+buttons[4]+buttons[6]+buttons[7]+buttons[8]+buttons[10]==51,buttons[0]+buttons[3]+buttons[5]+buttons[6]+buttons[9]+buttons[10]==66,buttons[0]+buttons[5]+buttons[7]+buttons[8]+buttons[9]==64,buttons[1]+buttons[5]+buttons[6]+buttons[7]+buttons[8]==60,buttons[0]+buttons[3]+buttons[5]+buttons[10]==45,buttons[1]+buttons[5]+buttons[7]+buttons[8]+buttons[9]+buttons[10]==48,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[7]+buttons[10]==67,buttons[0]+buttons[5]+buttons[7]+buttons[10]==47)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[10]==44,buttons[0]+buttons[7]+buttons[10]==19,buttons[0]+buttons[3]+buttons[4]+buttons[6]==35,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[7]+buttons[9]+buttons[10]==63,buttons[1]+buttons[2]+buttons[4]+buttons[10]==37,buttons[0]+buttons[4]+buttons[8]+buttons[10]==45,buttons[0]+buttons[2]+buttons[3]==12,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[7]+buttons[10]==57,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[8]+buttons[10]==73,buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[10]==54)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[4]==22,buttons[3]+buttons[4]+buttons[5]==33,buttons[2]+buttons[4]==14,buttons[1]+buttons[4]==16,buttons[0]+buttons[1]+buttons[4]==32,buttons[1]+buttons[3]==16,buttons[3]+buttons[4]+buttons[5]==33,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==63)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]==31,buttons[2]+buttons[4]==5,buttons[0]+buttons[1]+buttons[4]==199,buttons[0]+buttons[3]+buttons[4]==36,buttons[2]+buttons[3]==12)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[7]==48,buttons[3]+buttons[5]+buttons[6]==38,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]==41,buttons[1]+buttons[2]+buttons[5]+buttons[7]==21,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[6]==57,buttons[3]+buttons[4]+buttons[5]==30)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[4]==28,buttons[4]==19,buttons[1]+buttons[3]==15,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==70,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]==46,buttons[4]+buttons[5]==28,buttons[1]+buttons[2]+buttons[5]+buttons[6]==45)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[5]+buttons[6]==28,buttons[0]+buttons[3]+buttons[5]+buttons[7]==23,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]==71,buttons[3]+buttons[4]+buttons[8]==16,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==59,buttons[1]+buttons[4]+buttons[5]+buttons[7]==166,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[8]==175,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==45,buttons[3]+buttons[5]+buttons[8]==7,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[8]==203)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[4]==36,buttons[0]+buttons[1]==23,buttons[1]+buttons[3]+buttons[4]==23,buttons[0]+buttons[2]+buttons[4]==49,buttons[2]+buttons[4]==29,buttons[0]+buttons[2]+buttons[3]==37,buttons[1]+buttons[2]+buttons[3]+buttons[4]==36)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[4]==32,buttons[0]+buttons[2]+buttons[3]+buttons[5]==34,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==51,buttons[1]==10,buttons[0]+buttons[2]+buttons[3]+buttons[5]==34,buttons[0]+buttons[3]==6,buttons[0]+buttons[5]+buttons[6]==22,buttons[0]+buttons[2]+buttons[4]==32)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]+buttons[4]==29,buttons[0]+buttons[3]+buttons[4]==29,buttons[1]+buttons[4]==18,buttons[0]+buttons[2]==26,buttons[0]+buttons[2]+buttons[4]==39,buttons[1]+buttons[3]+buttons[4]==21)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[4]==25,buttons[1]+buttons[2]==8,buttons[0]==16,buttons[0]+buttons[3]+buttons[5]==23,buttons[0]+buttons[3]+buttons[4]+buttons[5]==32,buttons[1]+buttons[3]==10,buttons[0]+buttons[3]+buttons[4]==30,buttons[0]+buttons[2]==19)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(2) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]==6,buttons[1]==1,buttons[0]+buttons[1]==7,buttons[0]+buttons[1]==7)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]==22,buttons[2]+buttons[3]+buttons[5]+buttons[6]==37,buttons[0]+buttons[1]+buttons[6]==42,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[7]==50,buttons[2]+buttons[3]==17,buttons[1]+buttons[2]+buttons[3]+buttons[6]+buttons[7]==44,buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[7]==37,buttons[1]+buttons[2]+buttons[4]+buttons[7]==35)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]+buttons[4]==30,buttons[2]+buttons[3]+buttons[4]==24,buttons[0]+buttons[1]==6,buttons[0]+buttons[1]+buttons[4]==11,buttons[0]+buttons[3]+buttons[4]+buttons[5]==17)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]+buttons[4]+buttons[5]==25,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[6]==47,buttons[1]+buttons[2]==29,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[7]==53,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]==55,buttons[0]+buttons[3]+buttons[5]==19,buttons[1]+buttons[5]==26,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[7]==53,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]==38,buttons[1]+buttons[3]+buttons[4]+buttons[6]+buttons[7]==42)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[8]==54,buttons[1]+buttons[5]+buttons[6]+buttons[7]==47,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==52,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==72,buttons[0]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==53,buttons[1]+buttons[5]+buttons[6]+buttons[8]==51,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[6]==63,buttons[2]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==46,buttons[1]+buttons[3]+buttons[4]+buttons[6]==46)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[4]==4,buttons[2]+buttons[3]+buttons[4]==25,buttons[0]+buttons[1]+buttons[3]+buttons[5]==40,buttons[0]+buttons[1]+buttons[3]+buttons[5]==40,buttons[1]+buttons[2]+buttons[5]==39)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[7]==6,buttons[0]+buttons[4]+buttons[5]+buttons[7]==28,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[7]==50,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==34,buttons[0]+buttons[1]+buttons[3]+buttons[6]+buttons[7]+buttons[8]==45,buttons[4]+buttons[5]+buttons[6]+buttons[8]==24,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]==49)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(3) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]==10,buttons[0]+buttons[1]+buttons[2]==19,buttons[1]+buttons[2]==10,buttons[0]==9,buttons[0]+buttons[2]==18)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(12) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[4]+buttons[5]+buttons[11]==41,buttons[3]+buttons[6]+buttons[8]+buttons[9]+buttons[10]+buttons[11]==84,buttons[2]+buttons[4]+buttons[6]+buttons[7]+buttons[8]+buttons[9]+buttons[10]==89,buttons[3]+buttons[4]+buttons[7]==36,buttons[0]+buttons[2]+buttons[4]+buttons[8]+buttons[11]==54,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[9]+buttons[10]+buttons[11]==86,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[8]+buttons[9]+buttons[11]==81,buttons[3]+buttons[4]+buttons[6]+buttons[8]+buttons[10]+buttons[11]==68,buttons[3]+buttons[4]+buttons[6]+buttons[9]+buttons[11]==66,buttons[0]+buttons[1]+buttons[10]+buttons[11]==32)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[5]+buttons[7]==37,buttons[0]+buttons[1]+buttons[5]==35,buttons[0]+buttons[2]+buttons[4]+buttons[6]+buttons[7]==60,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==65,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]==56,buttons[4]+buttons[5]+buttons[6]+buttons[7]==50,buttons[0]+buttons[1]+buttons[2]+buttons[6]==45,buttons[0]+buttons[3]+buttons[4]+buttons[7]==55,buttons[0]+buttons[2]+buttons[3]+buttons[5]==48,buttons[0]+buttons[1]+buttons[2]+buttons[6]==45)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(2) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]==26,buttons[0]==11,buttons[1]==15,buttons[0]+buttons[1]==26)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]==178,buttons[1]+buttons[2]==35,buttons[0]==151,buttons[1]+buttons[3]==27,buttons[3]==10,buttons[0]+buttons[1]+buttons[2]+buttons[3]==196)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[3]+buttons[4]==32,buttons[0]+buttons[3]+buttons[4]+buttons[5]==36,buttons[0]+buttons[1]+buttons[3]+buttons[4]==32,buttons[2]+buttons[4]==6,buttons[1]+buttons[2]+buttons[5]==34,buttons[0]+buttons[1]+buttons[2]+buttons[3]==34)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]==45,buttons[0]+buttons[3]+buttons[5]==46,buttons[0]+buttons[2]+buttons[3]+buttons[4]==43,buttons[0]+buttons[1]+buttons[4]==17,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==50,buttons[1]+buttons[4]==2,buttons[2]+buttons[5]==37)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]==28,buttons[0]+buttons[2]+buttons[3]+buttons[7]==57,buttons[1]+buttons[2]+buttons[4]+buttons[6]+buttons[7]==78,buttons[1]+buttons[2]+buttons[3]+buttons[5]==48,buttons[0]+buttons[2]+buttons[3]==37,buttons[0]+buttons[1]+buttons[4]+buttons[6]==55,buttons[1]+buttons[3]+buttons[5]+buttons[6]==48)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[3]+buttons[4]==36,buttons[1]+buttons[2]+buttons[5]+buttons[6]==29,buttons[0]+buttons[5]+buttons[6]==24,buttons[0]+buttons[4]+buttons[5]+buttons[6]==37,buttons[3]+buttons[5]==6,buttons[2]==10,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==41)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[7]+buttons[8]==81,buttons[0]+buttons[1]+buttons[2]+buttons[6]+buttons[7]+buttons[8]==83,buttons[7]+buttons[8]==16,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[8]==82,buttons[2]+buttons[5]==30,buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==47,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[7]+buttons[8]==70,buttons[0]+buttons[3]+buttons[5]==46,buttons[0]+buttons[2]+buttons[6]+buttons[8]==64,buttons[0]+buttons[2]+buttons[3]+buttons[8]==61)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[4]+buttons[5]+buttons[7]==47,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[6]==77,buttons[3]+buttons[4]+buttons[7]==36,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==50,buttons[0]+buttons[3]+buttons[4]+buttons[7]==53,buttons[0]+buttons[4]+buttons[6]+buttons[7]==49,buttons[1]+buttons[3]+buttons[6]+buttons[7]==50,buttons[0]+buttons[2]+buttons[5]+buttons[6]+buttons[7]==70)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[5]==33,buttons[0]+buttons[4]+buttons[5]==30,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==37,buttons[1]==5,buttons[2]+buttons[4]==6,buttons[0]+buttons[1]+buttons[3]+buttons[5]==42,buttons[0]+buttons[2]+buttons[3]+buttons[5]==39,buttons[0]+buttons[4]==13)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]==16,buttons[0]+buttons[1]==20,buttons[1]+buttons[2]+buttons[3]==53,buttons[0]+buttons[3]==19)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[5]+buttons[6]+buttons[7]+buttons[9]==31,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[7]==49,buttons[0]+buttons[7]+buttons[9]==23,buttons[0]+buttons[4]+buttons[6]+buttons[7]+buttons[8]==45,buttons[2]+buttons[4]+buttons[5]+buttons[7]==48,buttons[0]+buttons[1]+buttons[3]+buttons[6]+buttons[7]==41,buttons[0]+buttons[4]+buttons[5]+buttons[6]+buttons[9]==48,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[9]==88)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]==199,buttons[1]+buttons[3]==6,buttons[0]+buttons[1]+buttons[2]+buttons[3]==195,buttons[1]+buttons[3]+buttons[5]+buttons[6]==12,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[7]==214,buttons[0]+buttons[2]+buttons[3]+buttons[6]==192,buttons[2]+buttons[3]+buttons[5]+buttons[7]==200,buttons[1]+buttons[3]+buttons[4]+buttons[6]==24,buttons[0]+buttons[2]+buttons[4]+buttons[6]==207)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(3) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]==159,buttons[1]+buttons[2]==143,buttons[0]+buttons[1]==143,buttons[1]+buttons[2]==143,buttons[1]==127)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[4]==30,buttons[1]+buttons[3]+buttons[4]==48,buttons[2]+buttons[3]==30,buttons[0]+buttons[1]+buttons[2]+buttons[4]==61,buttons[0]+buttons[1]+buttons[2]==43)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[4]==43,buttons[0]+buttons[2]+buttons[3]==25,buttons[1]+buttons[3]==17,buttons[2]+buttons[4]==31)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[6]+buttons[7]==24,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[9]==47,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[8]+buttons[9]==48,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[9]==37,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[8]+buttons[9]==50,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[8]==41,buttons[2]+buttons[8]+buttons[9]==8,buttons[1]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==40,buttons[0]+buttons[1]+buttons[2]+buttons[6]+buttons[7]+buttons[8]==24)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[8]+buttons[9]+buttons[10]==55,buttons[0]+buttons[2]+buttons[4]+buttons[8]+buttons[9]==63,buttons[2]+buttons[3]+buttons[5]+buttons[8]+buttons[9]==49,buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[10]==241,buttons[1]+buttons[2]+buttons[5]+buttons[9]==53,buttons[2]+buttons[3]+buttons[4]+buttons[7]+buttons[8]+buttons[9]==62,buttons[1]+buttons[4]+buttons[5]+buttons[7]+buttons[10]==47,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[7]+buttons[9]==72,buttons[0]+buttons[1]+buttons[2]+buttons[6]+buttons[7]==245,buttons[1]+buttons[5]+buttons[8]+buttons[9]==43)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(13) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[5]+buttons[6]+buttons[8]+buttons[11]==57,buttons[0]+buttons[2]+buttons[6]+buttons[8]+buttons[10]==61,buttons[2]+buttons[4]+buttons[7]+buttons[9]+buttons[11]==52,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[9]+buttons[11]==57,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[8]+buttons[11]==81,buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[9]+buttons[11]+buttons[12]==113,buttons[2]+buttons[5]+buttons[7]+buttons[8]+buttons[9]+buttons[10]+buttons[11]==101,buttons[0]+buttons[1]+buttons[5]+buttons[8]+buttons[11]==74,buttons[2]+buttons[8]+buttons[11]==39,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[8]+buttons[9]+buttons[11]==93)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[5]+buttons[8]+buttons[9]+buttons[10]==73,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[6]+buttons[8]+buttons[9]+buttons[10]==93,buttons[1]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[10]==54,buttons[1]+buttons[2]+buttons[5]+buttons[8]+buttons[9]+buttons[10]==73,buttons[2]+buttons[5]+buttons[6]+buttons[7]+buttons[9]+buttons[10]==66,buttons[0]+buttons[2]+buttons[5]+buttons[7]+buttons[8]+buttons[10]==63,buttons[0]+buttons[1]+buttons[3]+buttons[6]+buttons[7]+buttons[9]==61,buttons[1]+buttons[2]+buttons[6]+buttons[7]+buttons[9]+buttons[10]==70,buttons[1]+buttons[4]+buttons[7]+buttons[8]+buttons[10]==46,buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[9]+buttons[10]==78)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[7]==54,buttons[0]+buttons[1]+buttons[3]+buttons[8]+buttons[9]==59,buttons[1]+buttons[8]==19,buttons[1]+buttons[3]+buttons[6]==27,buttons[1]+buttons[4]+buttons[6]+buttons[8]+buttons[9]==57,buttons[3]+buttons[5]+buttons[7]+buttons[8]+buttons[9]==76,buttons[5]+buttons[7]+buttons[9]==41,buttons[1]+buttons[8]+buttons[9]==31)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[5]+buttons[6]==69,buttons[1]+buttons[2]+buttons[5]==49,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[7]==58,buttons[2]+buttons[5]+buttons[6]+buttons[7]==59,buttons[1]+buttons[3]+buttons[4]+buttons[7]==62,buttons[1]+buttons[3]+buttons[4]+buttons[5]==67,buttons[1]+buttons[6]+buttons[7]==50)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]==22,buttons[1]+buttons[3]==27,buttons[0]+buttons[3]==15,buttons[1]+buttons[2]==22,buttons[0]==3)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[4]+buttons[5]+buttons[6]+buttons[7]==95,buttons[1]+buttons[4]+buttons[5]==52,buttons[2]+buttons[4]+buttons[5]==50,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[6]==71,buttons[0]+buttons[2]+buttons[5]+buttons[6]+buttons[7]==75,buttons[5]+buttons[6]+buttons[7]==50,buttons[1]+buttons[4]+buttons[5]+buttons[6]==68,buttons[1]+buttons[3]+buttons[4]+buttons[7]==72,buttons[1]+buttons[6]==36,buttons[1]+buttons[2]+buttons[3]+buttons[4]==70)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(13) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[4]+buttons[6]+buttons[10]+buttons[11]==40,buttons[1]+buttons[4]+buttons[6]+buttons[9]+buttons[11]==56,buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[7]+buttons[9]==208,buttons[1]+buttons[6]+buttons[9]+buttons[10]+buttons[11]+buttons[12]==54,buttons[5]+buttons[8]+buttons[9]+buttons[10]+buttons[11]==49,buttons[1]+buttons[4]+buttons[11]+buttons[12]==39,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[10]+buttons[11]==215,buttons[1]+buttons[5]+buttons[6]+buttons[8]+buttons[9]+buttons[11]+buttons[12]==74,buttons[0]+buttons[5]+buttons[6]+buttons[7]+buttons[9]==53,buttons[0]+buttons[1]+buttons[4]+buttons[5]+buttons[6]+buttons[11]==55)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(3) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]==32,buttons[2]==13,buttons[0]+buttons[1]+buttons[2]==49,buttons[1]==19)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]==66,buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==55,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[6]==51,buttons[1]+buttons[2]+buttons[5]==23,buttons[0]+buttons[2]+buttons[5]+buttons[6]==34,buttons[3]+buttons[4]+buttons[5]+buttons[6]==36,buttons[0]+buttons[1]+buttons[2]+buttons[5]==38)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[5]+buttons[6]+buttons[8]+buttons[9]==60,buttons[1]+buttons[2]+buttons[4]+buttons[7]==25,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[9]==74,buttons[0]+buttons[1]+buttons[2]+buttons[7]+buttons[9]==57,buttons[0]+buttons[1]+buttons[4]+buttons[9]==53,buttons[0]+buttons[4]+buttons[5]+buttons[8]==32,buttons[0]+buttons[2]+buttons[4]+buttons[9]==42,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[7]+buttons[9]==80,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==38)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[5]==22,buttons[0]+buttons[2]+buttons[3]==13,buttons[0]+buttons[3]==9,buttons[1]+buttons[3]+buttons[4]==32)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(3) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]==10,buttons[0]+buttons[1]==16,buttons[1]+buttons[2]==21,buttons[1]+buttons[2]==21)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[8]==9,buttons[0]+buttons[3]+buttons[7]==8,buttons[4]==14,buttons[0]+buttons[8]==12,buttons[1]+buttons[2]+buttons[6]+buttons[8]+buttons[9]==52,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[9]==52,buttons[2]+buttons[3]+buttons[5]==19,buttons[0]+buttons[3]+buttons[6]+buttons[8]==29,buttons[0]+buttons[1]+buttons[3]+buttons[6]+buttons[7]+buttons[8]==49,buttons[0]+buttons[3]+buttons[4]+buttons[6]+buttons[8]==43)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(13) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]+buttons[5]+buttons[6]+buttons[7]+buttons[9]==51,buttons[1]+buttons[5]+buttons[6]+buttons[10]+buttons[11]+buttons[12]==76,buttons[3]+buttons[4]+buttons[6]+buttons[7]+buttons[8]+buttons[10]==57,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[10]+buttons[11]+buttons[12]==126,buttons[3]+buttons[5]+buttons[6]+buttons[10]+buttons[11]+buttons[12]==76,buttons[0]+buttons[3]+buttons[4]+buttons[5]+buttons[10]+buttons[12]==73,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[8]+buttons[10]+buttons[12]==102,buttons[3]+buttons[6]+buttons[7]+buttons[10]+buttons[12]==58,buttons[4]+buttons[5]+buttons[8]+buttons[11]+buttons[12]==60,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[8]+buttons[9]+buttons[11]+buttons[12]==121)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]==12,buttons[0]+buttons[3]==23,buttons[0]+buttons[2]==27,buttons[1]+buttons[2]+buttons[3]==19,buttons[1]+buttons[2]+buttons[3]==19)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[4]+buttons[7]==42,buttons[2]+buttons[4]+buttons[5]==37,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[7]==80,buttons[0]+buttons[4]+buttons[5]==38,buttons[2]+buttons[5]+buttons[7]==41,buttons[3]+buttons[6]==24,buttons[2]+buttons[3]==19,buttons[0]+buttons[2]==29,buttons[0]+buttons[1]+buttons[7]==46)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[4]+buttons[5]==57,buttons[1]+buttons[3]==23,buttons[0]==11,buttons[3]+buttons[4]==23,buttons[2]+buttons[5]==26,buttons[0]+buttons[1]+buttons[5]==40,buttons[2]+buttons[3]+buttons[5]==29)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[4]==23,buttons[1]+buttons[3]+buttons[5]==30,buttons[1]+buttons[2]+buttons[5]==26,buttons[2]+buttons[3]+buttons[5]+buttons[7]==31,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==52,buttons[1]+buttons[2]+buttons[3]+buttons[5]==42,buttons[2]+buttons[5]+buttons[6]==23,buttons[2]+buttons[4]+buttons[6]==32)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]==15,buttons[0]+buttons[2]+buttons[3]+buttons[4]==161,buttons[0]+buttons[2]+buttons[3]+buttons[4]==161,buttons[0]==6,buttons[1]+buttons[4]==13)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[4]==24,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]==100,buttons[0]+buttons[3]+buttons[7]==34,buttons[0]+buttons[2]+buttons[4]+buttons[6]+buttons[7]==54,buttons[0]+buttons[2]+buttons[7]==29,buttons[0]+buttons[1]+buttons[3]+buttons[5]+buttons[7]==64,buttons[0]+buttons[3]+buttons[4]+buttons[5]==39)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[5]==136,buttons[1]+buttons[4]==136,buttons[0]+buttons[1]+buttons[2]+buttons[5]==56,buttons[0]+buttons[1]+buttons[3]+buttons[4]==150)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[3]==42,buttons[3]==17,buttons[0]==9,buttons[0]+buttons[2]==15,buttons[0]+buttons[1]+buttons[2]==31,buttons[0]+buttons[1]+buttons[3]==42)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[5]==34,buttons[1]+buttons[4]==15,buttons[0]+buttons[2]+buttons[4]+buttons[5]==53,buttons[3]+buttons[4]+buttons[5]==30)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[9]+buttons[10]==166,buttons[0]+buttons[3]+buttons[10]==28,buttons[2]+buttons[3]+buttons[5]+buttons[10]==59,buttons[0]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[9]+buttons[10]==178,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[8]+buttons[10]==202,buttons[0]+buttons[3]+buttons[4]+buttons[6]==132,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[7]==168,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[6]==150,buttons[0]+buttons[5]+buttons[7]+buttons[8]+buttons[9]==62)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==47,buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==29,buttons[1]+buttons[3]+buttons[6]==34,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]==43,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[6]==61,buttons[2]+buttons[3]+buttons[4]+buttons[6]==38,buttons[1]+buttons[2]+buttons[3]+buttons[5]+buttons[6]==46,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==35)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==33,buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[8]+buttons[10]==207,buttons[1]+buttons[2]+buttons[6]+buttons[8]+buttons[9]==46,buttons[1]+buttons[5]+buttons[7]+buttons[9]==30,buttons[1]+buttons[3]+buttons[4]==45,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[7]+buttons[9]==55,buttons[0]+buttons[1]+buttons[4]+buttons[5]==44,buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]==40,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]+buttons[8]+buttons[9]+buttons[10]==230)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[3]+buttons[4]+buttons[6]==49,buttons[0]+buttons[5]==22,buttons[1]+buttons[4]+buttons[5]+buttons[6]==64,buttons[0]+buttons[3]+buttons[4]+buttons[6]==42,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[6]==58,buttons[3]+buttons[4]==20,buttons[1]+buttons[2]+buttons[6]==38,buttons[1]+buttons[2]+buttons[3]+buttons[6]==38)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[2]+buttons[3]+buttons[4]==62,buttons[1]+buttons[2]+buttons[5]==47,buttons[2]+buttons[3]+buttons[4]==43,buttons[1]+buttons[2]+buttons[3]==44,buttons[0]+buttons[1]+buttons[4]==55,buttons[5]==16,buttons[2]+buttons[3]+buttons[4]+buttons[5]==59,buttons[0]+buttons[1]+buttons[5]==53)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[4]==12,buttons[0]+buttons[1]+buttons[4]==27,buttons[2]+buttons[5]+buttons[6]==24,buttons[1]+buttons[2]+buttons[4]+buttons[5]==27,buttons[0]+buttons[1]+buttons[2]+buttons[3]==47,buttons[1]+buttons[2]+buttons[4]+buttons[6]==35,buttons[0]+buttons[3]+buttons[5]==27)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[4]+buttons[5]+buttons[8]==67,buttons[0]+buttons[2]==32,buttons[1]+buttons[3]+buttons[5]+buttons[6]==35,buttons[3]+buttons[4]+buttons[5]+buttons[6]==25,buttons[2]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==76,buttons[4]+buttons[7]==17,buttons[5]+buttons[6]+buttons[8]==43)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(2) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]==10,buttons[0]==14,buttons[1]==10,buttons[0]+buttons[1]==24)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[2]+buttons[3]+buttons[6]+buttons[9]==39,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[8]==64,buttons[0]+buttons[3]+buttons[5]+buttons[9]==40,buttons[0]+buttons[2]+buttons[5]+buttons[7]+buttons[8]+buttons[10]==62,buttons[0]+buttons[4]+buttons[5]+buttons[7]+buttons[9]==57,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]+buttons[9]==58,buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[9]+buttons[10]==96,buttons[0]+buttons[2]+buttons[3]+buttons[6]+buttons[9]==39,buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[7]==75)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(11) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[6]+buttons[7]+buttons[9]+buttons[10]==54,buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[10]==52,buttons[4]+buttons[5]+buttons[7]==31,buttons[2]+buttons[4]+buttons[6]+buttons[7]==55,buttons[0]+buttons[1]+buttons[4]+buttons[6]+buttons[10]==41,buttons[4]+buttons[8]+buttons[10]==36,buttons[3]+buttons[4]+buttons[7]+buttons[10]==36,buttons[2]+buttons[4]+buttons[7]+buttons[8]+buttons[9]+buttons[10]==75,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[8]+buttons[10]==85)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[5]==18,buttons[3]+buttons[4]+buttons[5]==18,buttons[1]+buttons[2]+buttons[4]==26,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]==50,buttons[0]+buttons[2]+buttons[3]+buttons[5]+buttons[6]==57)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[3]+buttons[6]+buttons[8]==33,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]+buttons[7]==46,buttons[3]+buttons[4]+buttons[5]==13,buttons[1]+buttons[4]+buttons[7]==32,buttons[0]+buttons[3]+buttons[6]+buttons[7]+buttons[8]==50,buttons[0]+buttons[7]+buttons[8]==34,buttons[3]+buttons[4]+buttons[7]+buttons[8]==47)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(6) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[1]+buttons[4]+buttons[5]==27,buttons[2]+buttons[4]+buttons[5]==40,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]==63,buttons[1]+buttons[5]==14,buttons[2]+buttons[3]+buttons[5]==30,buttons[0]+buttons[2]+buttons[4]+buttons[5]==60,buttons[0]+buttons[2]+buttons[4]==53)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[6]==2,buttons[3]+buttons[4]+buttons[5]==36,buttons[1]+buttons[2]+buttons[3]+buttons[4]==45,buttons[6]==2,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]==50,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[6]==47,buttons[0]+buttons[1]+buttons[2]+buttons[5]==53,buttons[0]+buttons[2]+buttons[4]+buttons[5]==45,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[6]==53)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]==52,buttons[2]+buttons[3]+buttons[6]==27,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==42,buttons[1]+buttons[3]+buttons[4]==33,buttons[1]+buttons[5]+buttons[6]==29)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(10) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[4]==35,buttons[0]+buttons[4]+buttons[7]+buttons[8]+buttons[9]==58,buttons[0]+buttons[2]+buttons[4]+buttons[5]+buttons[7]+buttons[8]==56,buttons[3]+buttons[5]==9,buttons[0]+buttons[7]+buttons[9]==32,buttons[1]+buttons[4]+buttons[5]+buttons[8]==50,buttons[0]+buttons[4]+buttons[5]+buttons[8]==39,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[9]==60,buttons[0]+buttons[3]+buttons[5]+buttons[6]==13)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(8) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]==50,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]==79,buttons[4]+buttons[5]+buttons[6]==32,buttons[1]+buttons[2]==25,buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]==69,buttons[1]+buttons[4]+buttons[5]+buttons[7]==49)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(9) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[4]+buttons[6]+buttons[8]==71,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[8]==99,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[7]+buttons[8]==64,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]+buttons[7]==64,buttons[1]+buttons[3]+buttons[4]+buttons[6]==36,buttons[2]+buttons[4]+buttons[6]+buttons[8]==48,buttons[2]+buttons[8]==23,buttons[0]+buttons[1]+buttons[2]+buttons[4]==39,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[6]==54)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]==40,buttons[1]+buttons[3]+buttons[4]+buttons[6]==19,buttons[1]+buttons[4]+buttons[5]+buttons[6]==12,buttons[3]+buttons[4]+buttons[5]==26,buttons[0]+buttons[1]+buttons[2]+buttons[5]+buttons[6]==33,buttons[2]+buttons[3]+buttons[4]==23)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]+buttons[5]+buttons[6]==147,buttons[0]+buttons[2]+buttons[6]==38,buttons[1]+buttons[2]+buttons[6]==41,buttons[2]+buttons[4]+buttons[6]==22,buttons[4]+buttons[6]==11,buttons[1]+buttons[2]+buttons[3]+buttons[4]==36)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(5) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[4]==41,buttons[1]+buttons[3]+buttons[4]==46,buttons[0]+buttons[1]+buttons[2]==29,buttons[1]+buttons[2]+buttons[3]+buttons[4]==48,buttons[1]+buttons[2]==18,buttons[0]==11,buttons[0]+buttons[4]==25)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[3]+buttons[4]+buttons[6]==197,buttons[0]+buttons[3]+buttons[5]==37,buttons[0]+buttons[1]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]==229,buttons[0]+buttons[1]+buttons[2]+buttons[4]+buttons[5]==50,buttons[1]+buttons[2]+buttons[4]==32,buttons[0]+buttons[2]+buttons[3]+buttons[5]==47,buttons[4]+buttons[5]==26,buttons[0]+buttons[2]+buttons[4]+buttons[6]==178,buttons[0]+buttons[4]+buttons[5]+buttons[6]==186)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(7) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[2]+buttons[4]+buttons[5]+buttons[6]==42,buttons[0]+buttons[2]+buttons[3]+buttons[4]==43,buttons[0]+buttons[2]==31,buttons[0]+buttons[4]+buttons[6]==29,buttons[1]+buttons[2]+buttons[3]==33)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(13) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[4]+buttons[5]+buttons[6]+buttons[10]+buttons[11]+buttons[12]==55,buttons[2]+buttons[3]+buttons[5]+buttons[9]+buttons[10]+buttons[11]+buttons[12]==62,buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[9]+buttons[11]+buttons[12]==69,buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[9]+buttons[10]+buttons[11]==54,buttons[1]+buttons[2]+buttons[3]+buttons[6]+buttons[7]+buttons[9]+buttons[10]+buttons[11]==48,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[6]+buttons[7]+buttons[10]+buttons[12]==47,buttons[0]+buttons[2]+buttons[4]+buttons[7]+buttons[8]+buttons[9]+buttons[10]+buttons[11]==67,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[7]+buttons[9]+buttons[10]+buttons[11]==78,buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[7]+buttons[9]+buttons[11]==53,buttons[0]+buttons[2]+buttons[3]+buttons[4]+buttons[5]+buttons[6]+buttons[7]+buttons[9]+buttons[10]+buttons[11]==75)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(4) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[1]+buttons[2]+buttons[3]==58,buttons[3]==13,buttons[0]+buttons[1]+buttons[3]==41,buttons[1]+buttons[2]==25,buttons[0]==20,buttons[0]+buttons[2]+buttons[3]==50)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
o = Optimize()
buttons = [ Int('button%s' % i) for i in range(12) ]
o.add(*[i >= 0 for i in buttons])
presses = Int('presses')
o.add(buttons[0]+buttons[3]+buttons[8]+buttons[10]==42,buttons[0]+buttons[3]+buttons[4]+buttons[6]+buttons[7]==229,buttons[0]+buttons[1]+buttons[2]+buttons[4]==30,buttons[0]+buttons[4]+buttons[5]+buttons[7]+buttons[10]+buttons[11]==234,buttons[4]+buttons[6]+buttons[10]==30,buttons[0]+buttons[1]+buttons[3]+buttons[4]+buttons[5]+buttons[8]+buttons[10]==66,buttons[2]+buttons[4]+buttons[6]+buttons[9]+buttons[10]==49,buttons[2]+buttons[4]+buttons[5]+buttons[6]+buttons[9]==52,buttons[0]+buttons[4]+buttons[6]+buttons[11]==37,buttons[1]+buttons[2]+buttons[5]+buttons[6]+buttons[10]==44)
o.add(sum(buttons)==presses)
o.minimize(presses)
o.check()
print(o.model()[presses])
